### ISSUE TITLE
Error when installing on Raspberry Pi

### ISSUE THREAD

**Issue by ijo-amali** [Muges/audiotsm#4]
When using both `pip` and `pip3` to install this package on a Raspberry Pi 3 B+, it gives this error:
```
Could not find a version that satisfies the requirement autiotsm (from versions: )
No matching distribution found for autiotsm
```

**Comment by Gilbert189** [comment]
It's audiotsm, not autiotsm.

**Comment by ijo-amali** [comment]
A year and a half late, but thanks anyways lol
